---
title: "Decision Tool Project"
date:  "SYS 6014 Decision Analysis Spring 2020"
output: github_document
---

This course includes a semester-long project to build a working decision model. Ideally, this project will relate closely to the student’s own dissertation research, professional practice, or other domain application that interests them. 

For example, if the student is developing a machine learning application for their research, a good project might involve using the predictions generated by their model as inputs to a decision tool. The hope is that these projects could form the basis for subsequent research papers, dissertation chapters, or other professional work products, for interested students.


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```






# FAQs

## Can we do a project as a team?

Yes, but with conditions. 

*Your team must be self-organizaing.* You form your own team voluntarily.

*Don't bring the instructor any drama.* In group interactions, frictions can sometimes arise. Sorting out such frictions is entirely the responsibility of the team members themselves. It will not be appropriate to ask the instructor to sort out intra-team dynamics. If (say) one team member is not performing his fair share of the work, that is a shame - but it is no one else's responsibility. All team work will be submitted jointly and graded equally.